# Generated by Django 3.1.6 on 2021-03-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210220_1212'),
        ('product', '0004_auto_20210303_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='product_type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
