# Generated by Django 3.1.6 on 2021-03-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210304_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_time',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Shipping_detail',
        ),
    ]
