# Generated by Django 3.1.6 on 2021-02-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='packet',
        ),
    ]
