# Generated by Django 3.1.6 on 2021-02-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210216_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
